import type { Locale } from "@/i18n/store";

export type Localized = Record<Locale, string>;

export interface ProjectLinks {
  repo?: string;
  demo?: string;
  video?: string;
  /** When true, the repo is private — UI shows a label instead of a broken link. */
  private?: boolean;
}

export interface ProjectDemo {
  /** embed = self-hosted iframe under /demos; live = external URL; none = no live demo. */
  kind: "embed" | "live" | "none";
  /** For embed: path like "/demos/<id>/index.html". For live: the external URL. */
  src?: string;
  /** Public URL shown as an "open live" button (in addition to an embed). */
  live?: string;
  /** Fallback image shown if there is no embed or the iframe fails to load. */
  poster?: string;
}

/** Screenshots of the project rendered on different devices (for the showcase). */
export interface ProjectPreview {
  desktop?: string;
  tablet?: string;
  mobile?: string;
}

export interface Project {
  id: string;
  title: string;
  tagline: Localized;
  description: Localized;
  /** Technologies / role on the project. */
  tech: string[];
  role: Localized;
  /** High-level categories, e.g. Web, SaaS, 3D. */
  tags: string[];
  links: ProjectLinks;
  /** Paths to images/video under /public, e.g. "/projects/<id>/cover.webp". */
  media: string[];
  /** Device screenshots shown before the interactive demo, generated by
   *  scripts/capture-shots.mjs into /public/projects/<id>/. */
  preview?: ProjectPreview;
  /** Optional embedded "mini functional model" of the project. */
  demo?: ProjectDemo;
}
